2020-04-22 21:53:44,508 ERROR: Exception on /explore [GET] [in /home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lutz/Development/databas/app/routes.py", line 53, in explore
    next_url=next_url, prev_url=prev_url)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/lutz/Development/databas/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/lutz/Development/databas/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/home/lutz/Development/databas/app/templates/base.html", line 51, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/lutz/Development/databas/app/templates/index.html", line 18, in block "app_content"
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/wtf.html", line 157, in template
    document is interpreted as a reference to the start of that document,
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-04-22 21:53:51,939 INFO: Microblog startup [in /home/lutz/Development/databas/app/__init__.py:47]
2020-04-22 21:58:53,077 INFO: Microblog startup [in /home/lutz/Development/databas/app/__init__.py:47]
2020-04-22 22:07:36,611 INFO: Microblog startup [in /home/lutz/Development/databas/app/__init__.py:47]
2020-04-23 09:08:26,239 INFO: Microblog startup [in /home/lutz/Development/databas/app/__init__.py:47]
2020-04-23 09:08:29,951 ERROR: Exception on /index [GET] [in /home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lutz/Development/databas/app/routes.py", line 23, in index
    form = BookingForm()
NameError: name 'BookingForm' is not defined
2020-04-23 09:08:31,216 ERROR: Exception on /index [GET] [in /home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lutz/Development/databas/app/routes.py", line 23, in index
    form = BookingForm()
NameError: name 'BookingForm' is not defined
2020-04-23 09:08:52,513 INFO: Microblog startup [in /home/lutz/Development/databas/app/__init__.py:47]
2020-04-23 09:08:55,307 ERROR: Exception on /index [GET] [in /home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lutz/Development/databas/app/routes.py", line 23, in index
    form = BookingForm()
NameError: name 'BookingForm' is not defined
2020-04-23 09:08:57,363 ERROR: Exception on /index [GET] [in /home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lutz/Development/databas/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lutz/Development/databas/app/routes.py", line 23, in index
    form = BookingForm()
NameError: name 'BookingForm' is not defined
